### ISSUE TITLE
how i add label hacktoberfest for my pull request

### ISSUE THREAD

**Issue by huyrua291996** [suspended/hack-hacktoberfest#62]

**Comment by xRahul** [comment]
@huyrua291996 you can't add labels unless you have the access to the project.

**Comment by huyrua291996** [comment]
thanks

**Comment by huyrua291996** [comment]
i wonder that i have to creat 4 pull request with label Hacktoberfest or not

**Comment by xRahul** [comment]
No you just create the pr, we'll add the label
